/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActiveFilters: typeof import('./components/ActiveFilters.vue')['default']
    AdminAllSourcesPanel: typeof import('./components/admin/AdminAllSourcesPanel.vue')['default']
    AdminConfigPanel: typeof import('./components/admin/AdminConfigPanel.vue')['default']
    AdminEngagementPanel: typeof import('./components/admin/AdminEngagementPanel.vue')['default']
    AdminFileSourcesPanel: typeof import('./components/admin/AdminFileSourcesPanel.vue')['default']
    AdminFiletypesPanel: typeof import('./components/admin/AdminFiletypesPanel.vue')['default']
    AdminGroup: typeof import('./components/admin/AdminGroup.vue')['default']
    AdminPanel: typeof import('./components/admin/AdminPanel.vue')['default']
    AdminPathFiltersPanel: typeof import('./components/admin/AdminPathFiltersPanel.vue')['default']
    AdminScanPanel: typeof import('./components/admin/AdminScanPanel.vue')['default']
    AdminSourceTreePanel: typeof import('./components/admin/AdminSourceTreePanel.vue')['default']
    AdminSqlSourceForm: typeof import('./components/admin/AdminSqlSourceForm.vue')['default']
    AdminSqlSourcesPanel: typeof import('./components/admin/AdminSqlSourcesPanel.vue')['default']
    AdminStatusPanel: typeof import('./components/admin/AdminStatusPanel.vue')['default']
    AdminTreeNode: typeof import('./components/admin/AdminTreeNode.vue')['default']
    AdminUiConfigPanel: typeof import('./components/admin/AdminUiConfigPanel.vue')['default']
    AdminWebSourcesPanel: typeof import('./components/admin/AdminWebSourcesPanel.vue')['default']
    AlertsPanel: typeof import('./components/AlertsPanel.vue')['default']
    CollapsiblePanel: typeof import('./components/CollapsiblePanel.vue')['default']
    CollectionsPanel: typeof import('./components/CollectionsPanel.vue')['default']
    DocumentDetailModal: typeof import('./components/DocumentDetailModal.vue')['default']
    DsfrAlert: typeof import('@gouvminint/vue-dsfr')['DsfrAlert']
    DsfrBadge: typeof import('@gouvminint/vue-dsfr')['DsfrBadge']
    DsfrButton: typeof import('@gouvminint/vue-dsfr')['DsfrButton']
    DsfrFooter: typeof import('@gouvminint/vue-dsfr')['DsfrFooter']
    DsfrHeader: typeof import('@gouvminint/vue-dsfr')['DsfrHeader']
    DsfrModal: typeof import('@gouvminint/vue-dsfr')['DsfrModal']
    DsfrPagination: typeof import('@gouvminint/vue-dsfr')['DsfrPagination']
    DsfrSearchBar: typeof import('@gouvminint/vue-dsfr')['DsfrSearchBar']
    DsfrSelect: typeof import('@gouvminint/vue-dsfr')['DsfrSelect']
    DsfrSkipLinks: typeof import('@gouvminint/vue-dsfr')['DsfrSkipLinks']
    FacetGroup: typeof import('./components/FacetGroup.vue')['default']
    FacetsSidebar: typeof import('./components/FacetsSidebar.vue')['default']
    FeedbackBar: typeof import('./components/FeedbackBar.vue')['default']
    NpsModal: typeof import('./components/NpsModal.vue')['default']
    ResultCard: typeof import('./components/ResultCard.vue')['default']
    ResultsList: typeof import('./components/ResultsList.vue')['default']
    ResultsToolbar: typeof import('./components/ResultsToolbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterLinkShim: typeof import('./components/RouterLinkShim.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    SavedSearchesPanel: typeof import('./components/SavedSearchesPanel.vue')['default']
    SelectionToolbar: typeof import('./components/SelectionToolbar.vue')['default']
    SourcesSelect: typeof import('./components/SourcesSelect.vue')['default']
    StatsAuditLogPanel: typeof import('./components/stats/StatsAuditLogPanel.vue')['default']
    StatsNpsPanel: typeof import('./components/stats/StatsNpsPanel.vue')['default']
    StatsPager: typeof import('./components/stats/StatsPager.vue')['default']
    StatsPanel: typeof import('./components/stats/StatsPanel.vue')['default']
    StatsSearchLogsPanel: typeof import('./components/stats/StatsSearchLogsPanel.vue')['default']
    StatsSuggestionsPanel: typeof import('./components/stats/StatsSuggestionsPanel.vue')['default']
    StatsSummaryPanel: typeof import('./components/stats/StatsSummaryPanel.vue')['default']
    StatsZeroResultsPanel: typeof import('./components/stats/StatsZeroResultsPanel.vue')['default']
    SuggestionModal: typeof import('./components/SuggestionModal.vue')['default']
  }
}
